#!/bin/zsh

local result=$({
  zoxide query --list 2>/dev/null
  ghq list -p
  fd -H -d 2 -t d . "$HOME"
} | awk '!seen[$0]++' | fzf \
  --layout=reverse \
  --query="$LBUFFER" \
  --preview "ls -a --color=always {}")

if [ -n "$result" ]; then
  BUFFER="cd $result"
  zle accept-line
fi
zle reset-prompt
