#!/bin/zsh

cache_init starship "starship init zsh"
cache_init zoxide  "zoxide init zsh"
cache_init docker  "docker completion zsh"

zsh-defer -c 'eval "$(fnm env --shell zsh --use-on-cd --version-file-strategy=recursive --resolve-engines)"'
source "$HOME/.deno/env"

if ! whence -p wezterm > /dev/null; then
  echo "\033[1;33mwarning\033[m no Linux wezterm on \$PATH"
fi
source "$HOME/.config/zsh/wezterm_shell_integration.sh"

if [[ -f "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

ensure_zcompiled "$HOME/.config/zsh/.zshrc"
