local wezterm = require 'wezterm'
local act = wezterm.action
local workspace = require 'workspace'

return {
  keys = {
    { key = 'Tab', mods = 'CTRL', action = act.ActivateTabRelative(1) },
    { key = 'Tab', mods = 'SHIFT|CTRL', action = act.ActivateTabRelative(-1) },
    { key = 'Enter', mods = 'CTRL', action = act.SendString '\x1b[13;5u' },
    { key = "Enter", mods = "SHIFT", action = act.SendString("\n") },
    { key = ".", mods = "CTRL", action = act.SendString("\x1b[46;5u") },
    { key = 't', mods = 'CTRL', action = act.SpawnCommandInNewTab { cwd = '~', }, },
    { key = 'w', mods = 'CTRL', action = act.CloseCurrentTab{ confirm = false } },
    { key = 'C', mods = 'CTRL', action = act.CopyTo 'Clipboard' },
    { key = 'F', mods = 'CTRL', action = act.SendString '\x1b[70;5u' },
    { key = 'H', mods = 'CTRL', action = act.ActivatePaneDirection 'Left' },
    { key = 'J', mods = 'CTRL', action = act.ActivatePaneDirection 'Down' },
    { key = 'K', mods = 'CTRL', action = act.ActivatePaneDirection 'Up' },
    { key = 'L', mods = 'CTRL', action = act.ActivatePaneDirection 'Right' },
    { key = 'N', mods = 'CTRL', action = act.SpawnWindow },
    { key = 'P', mods = 'CTRL', action = act.ActivateCommandPalette },
    { key = 'Q', mods = 'CTRL', action = act.QuitApplication },
    { key = 'R', mods = 'CTRL', action = act.ReloadConfiguration },
    { key = 'T', mods = 'CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
    { key = 'V', mods = 'CTRL', action = act.PasteFrom 'Clipboard' },
    { key = 'X', mods = 'CTRL', action = act.ActivateCopyMode },
    { key = 'Z', mods = 'CTRL', action = act.TogglePaneZoomState },
    { key = 'h', mods = 'ALT', action = act.SendKey { key = "LeftArrow" }},
    { key = 'j', mods = 'ALT', action = act.SendKey { key = "DownArrow" }},
    { key = 'k', mods = 'ALT', action = act.SendKey { key = "UpArrow" }},
    { key = 'l', mods = 'ALT', action = act.SendKey { key = "RightArrow" }},
    { key = 'H', mods = 'ALT', action = act.SendKey { key = "Home" }},
    { key = 'L', mods = 'ALT', action = act.SendKey { key = "End" }},
    { key = '/', mods = 'LEADER', action = act.Search 'CurrentSelectionOrEmptyString' },
    { key = "h", mods = "LEADER", action = act.SplitVertical { domain = "CurrentPaneDomain" } },
    { key = "v", mods = "LEADER", action = act.SplitHorizontal { domain = "CurrentPaneDomain" } },
    { key = 'p', mods = "LEADER", action = act.ActivateKeyTable { name = "pane_mode", one_shot = false, prevent_fallback = true } },
    { key = "q", mods = "LEADER", action = act.CloseCurrentPane { confirm = false } },
    { key = 'phys:Space', mods = 'SHIFT|CTRL', action = act.QuickSelect },
    { key = 's', mods = 'CTRL|ALT', action = act.ToggleFloatingPane },
    -- Workspace
    { key = 'l', mods = 'CTRL|ALT', action = workspace.switch_to_workspace('next') },
    { key = 'h', mods = 'CTRL|ALT', action = workspace.switch_to_workspace('prev') },
    { key = 'w', mods = 'LEADER', action = workspace.workspace_selector() },
  },

  key_tables = {
    copy_mode = {
      { key = 'Tab', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
      { key = 'Tab', mods = 'SHIFT', action = act.CopyMode 'MoveBackwardWord' },
      { key = 'Enter', mods = 'NONE', action = act.CopyMode 'MoveToStartOfNextLine' },
      { key = 'Escape', mods = 'NONE', action = act.CopyMode 'Close' },
      { key = 'Space', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
      { key = '$', mods = 'NONE', action = act.CopyMode 'MoveToEndOfLineContent' },
      { key = '$', mods = 'SHIFT', action = act.CopyMode 'MoveToEndOfLineContent' },
      { key = ',', mods = 'NONE', action = act.CopyMode 'JumpReverse' },
      { key = '0', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLine' },
      { key = ';', mods = 'NONE', action = act.CopyMode 'JumpAgain' },
      { key = 'F', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
      { key = 'F', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
      { key = 'G', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackBottom' },
      { key = 'G', mods = 'SHIFT', action = act.CopyMode 'MoveToScrollbackBottom' },
      { key = 'H', mods = 'NONE', action = act.CopyMode 'MoveToViewportTop' },
      { key = 'H', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportTop' },
      { key = 'L', mods = 'NONE', action = act.CopyMode 'MoveToViewportBottom' },
      { key = 'L', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportBottom' },
      { key = 'M', mods = 'NONE', action = act.CopyMode 'MoveToViewportMiddle' },
      { key = 'M', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportMiddle' },
      { key = 'O', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
      { key = 'O', mods = 'SHIFT', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
      { key = 'T', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
      { key = 'T', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
      { key = 'V', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Line' } },
      { key = 'V', mods = 'SHIFT', action = act.CopyMode{ SetSelectionMode =  'Line' } },
      { key = '^', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLineContent' },
      { key = '^', mods = 'SHIFT', action = act.CopyMode 'MoveToStartOfLineContent' },
      { key = 'b', mods = 'NONE', action = act.CopyMode 'MoveBackwardWord' },
      { key = 'b', mods = 'ALT', action = act.CopyMode 'MoveBackwardWord' },
      { key = 'b', mods = 'CTRL', action = act.CopyMode 'PageUp' },
      { key = 'c', mods = 'CTRL', action = act.CopyMode 'Close' },
      { key = 'd', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (0.5) } },
      { key = 'e', mods = 'NONE', action = act.CopyMode 'MoveForwardWordEnd' },
      { key = 'f', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = false } } },
      { key = 'f', mods = 'ALT', action = act.CopyMode 'MoveForwardWord' },
      { key = 'f', mods = 'CTRL', action = act.CopyMode 'PageDown' },
      { key = 'g', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackTop' },
      { key = 'g', mods = 'CTRL', action = act.CopyMode 'Close' },
      { key = 'h', mods = 'NONE', action = act.CopyMode 'MoveLeft' },
      { key = 'j', mods = 'NONE', action = act.CopyMode 'MoveDown' },
      { key = 'k', mods = 'NONE', action = act.CopyMode 'MoveUp' },
      { key = 'l', mods = 'NONE', action = act.CopyMode 'MoveRight' },
      { key = 'm', mods = 'ALT', action = act.CopyMode 'MoveToStartOfLineContent' },
      { key = 'o', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEnd' },
      { key = 'q', mods = 'NONE', action = act.CopyMode 'Close' },
      { key = 't', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = true } } },
      { key = 'u', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (-0.5) } },
      { key = 'v', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
      { key = 'v', mods = 'CTRL', action = act.CopyMode{ SetSelectionMode =  'Block' } },
      { key = 'w', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
      { key = 'y', mods = 'NONE', action = act.Multiple{ { CopyTo =  'ClipboardAndPrimarySelection' }, { CopyMode =  'Close' } } },
    },

    search_mode = {
      { key = 'Enter', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
      { key = 'Escape', mods = 'NONE', action = act.CopyMode 'Close' },
      { key = 'n', mods = 'CTRL', action = act.CopyMode 'NextMatch' },
      { key = 'p', mods = 'CTRL', action = act.CopyMode 'PriorMatch' },
      { key = 'r', mods = 'CTRL', action = act.CopyMode 'CycleMatchType' },
      { key = 'u', mods = 'CTRL', action = act.CopyMode 'ClearPattern' },
      { key = 'PageUp', mods = 'NONE', action = act.CopyMode 'PriorMatchPage' },
      { key = 'PageDown', mods = 'NONE', action = act.CopyMode 'NextMatchPage' },
      { key = 'UpArrow', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
      { key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'NextMatch' },
    },

    pane_mode = {
      { key = 'h', action = act.ActivatePaneDirection 'Left' },
      { key = 'j', action = act.ActivatePaneDirection 'Down' },
      { key = 'k', action = act.ActivatePaneDirection 'Up' },
      { key = 'l', action = act.ActivatePaneDirection 'Right' },
      { key = 'v', mods = 'CTRL', action = act.SplitVertical },
      { key = 'h', mods = 'CTRL', action = act.SplitHorizontal },
      { key = 'h', mods = 'ALT', action = act.AdjustPaneSize { 'Left', 1 } },
      { key = 'j', mods = 'ALT', action = act.AdjustPaneSize { 'Down', 1 } },
      { key = 'k', mods = 'ALT', action = act.AdjustPaneSize { 'Up', 1 } },
      { key = 'l', mods = 'ALT', action = act.AdjustPaneSize { 'Right', 1 } },
      { key = "w", action = act.CloseCurrentPane { confirm = false } },
      { key = "q", action = 'PopKeyTable' },
      { key = 'Escape', action = act.Multiple({ 'PopKeyTable', act.SendKey({ key = 'Escape' }) }) },
    },

    workspace_mode = {
      { key = 'c', mods = 'SHIFT', action = workspace.create_workspace() },
      { key = 'Escape', action = act.Multiple({ 'PopKeyTable', act.SendKey({ key = 'Escape' }) }) },
    },

    floating_modal = {
      { key = 'h', mods = 'ALT', action = act.FloatingModal 'MoveLeft' },
      { key = 'j', mods = 'ALT', action = act.FloatingModal 'MoveDown' },
      { key = 'k', mods = 'ALT', action = act.FloatingModal 'MoveUp' },
      { key = 'l', mods = 'ALT', action = act.FloatingModal 'MoveRight' },
    },
  }
}
