history:
  defaultScope: global
  redact: []
  keymap:
    deleteSoft: ctrl-d
    deleteHard: alt-d
    toggleScope: ctrl-r
    togglePreview: ?

snippets:
# snippet and keyword abbrev
- name: git status
  keyword: gs
  snippet: git status --short --branch

- name: git log
  keyword: gl
  snippet: git log --oneline

# snippet with placeholder
- name: git commit message
  keyword: gcim
  snippet: git commit -m '{{commit_message}}'

- name: "null"
  keyword: "null"
  snippet: ">/dev/null 2>&1"
  # auto expand condition
  # If not defined, it is only valid at the beginning of a line.
  context:
    # buffer: ''
    lbuffer: '.+\s'
    # rbuffer: ''

- name: Edit Note
  keyword: nbe
  snippet: nb edit

- name: List Note
  keyword: nbl
  snippet: nb ls --limit 20

- name: List All Note
  keyword: nbla
  snippet: nb ls --all

- name: nb article
  keyword: nbar
  snippet: nb-article {{}}

- name: "docker compose"
  keyword: "dc"
  snippet: "docker compose"
  
- name: "windows dir"
  keyword: "win"
  snippet: "/mnt/c/{{dir}}"
  context:
    lbuffer: '.+\s'

- name: branch
  keyword: B
  snippet: git symbolic-ref --short HEAD
  context:
    lbuffer: '^git\s+checkout\s+'
  evaluate: true # eval snippet

completions:
# simple sourceCommand, no callback
- name: kill signal
  patterns:
    - "^kill -s $"
  sourceCommand: "kill -l | tr ' ' '\\n'"
  options:
    --prompt: "'Kill Signal> '"

# use excludePatterns and callback
- name: kill pid
  patterns:
    - "^kill( .*)? $"
  excludePatterns:
    # -l, -n or -s is followed by SIGNAL instead of PID
    - " -[lns] $"
  sourceCommand: "LANG=C ps -ef | sed 1d"
  options:
    --multi: true
    --prompt: "'Kill Process> '"
  callback: "awk '{print $2}'"

# Use null (\0) termination Input / Output
- name: chdir
  patterns:
    - "^cd $"
  sourceCommand: "fd -t d --hidden --max-depth 5 --exclude '.git' -0"
  options:
    # Added --read0 if null termination is used in `sourceCommand` output.
    --read0: true
    --prompt: "'Chdir> '"
    --preview: "ls -AF --color=always {}"
  callback: "batcat"
  callbackZero: true # null termination is used in `callback` I/O

- name: nb edit
  patterns:
    - "^nb e( .*)? $"
    - "^nb edit( .*)? $"
  sourceCommand: "nb ls --no-color | grep -E '^\\[[0-9]+\\]'"
  options:
    --ansi: true
    --prompt: "'nb edit >'"
    --preview: "echo {} | sed -E 's/^\\[([0-9]+)\\].*/\\1/' | xargs nb show"
  callback: "sed -E 's/^\\[([0-9]+)\\].*/\\1/'"

- name: nb subcommands
  patterns:
    - ^\s*nb\s*$
    - ^\s*nb\s+help\s*$
  sourceCommand: nb subcommands
  options:
    --prompt: "'nb subcommand >'"
