format = """
[╭─ ](purple)\
$os \
$username \
$hostname \
$directory\
$git_branch
[╰ ](purple)\
$python\
$rust\
$nodejs \
${env_var.VIRTUAL_ENV}  \
$character
"""

right_format = "$ruby"

[os]
format = "[$symbol]($style)"
style = "purple"
disabled = false

[os.symbols]
Ubuntu = "󰕈"
Windows = "󰖳"

[username]
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = true
trim_at = "."
detect_env_vars = []
format = "[@$hostname]($style)"
disabled = false

[directory]
truncate_to_repo = true
truncation_symbol = "…/"
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
style = "purple"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[python]
format = "[$symbol($version)]($style)"

[rust]
format = "[$symbol($version)]($style)"

[nodejs]
format = "[$symbol($version)]($style)"

[env_var.VIRTUAL_ENV]
format = "[󰆧]($style)"
style = "yellow"

[character]
success_symbol = '[\$](bold green) '
error_symbol = '[\$](bold green) '
